---

repositories:
  -
    name: asteris-mantl-rpm
    baseurl: https://dl.bintray.com/asteris/mantl-rpm
    gpgcheck: 0
    enabled: 1
  -
    name: ciscocloud-rpm
    baseurl: https://dl.bintray.com/ciscocloud/rpm
    gpgcheck: 0
    enabled: 1
