---
- name: install vault
  sudo: yes
  yum:
    name: "{{ vault_package }}"
    state: present
  tags:
    - vault
    - bootstrap

- name: configure vault
  sudo: yes
  template:
    src: vault.hcl.j2
    dest: /etc/vault/vault.hcl
  tags:
    - vault
  when: vault_is_server

- name: enable vault
  sudo: yes
  service:
    name: vault
    enabled: yes
    state: started
  tags:
    - vault
  when: vault_is_server

- name: wait for vault port
  wait_for:
    port: "{{vault_default_port}}"
  tags:
    - vault
  when: vault_is_server

- include: bootstrap.yml
  when: vault_is_server

- name: set token ttl
  shell: VAULT_TOKEN={{vault_root_token}} vault mount-tune -default-lease-ttl={{ vault_token_default_ttl }}s -max-lease-ttl={{ vault_token_max_ttl }}s auth/token
  no_log: true
  tags:
    - vault
  when: vault_is_server

- name: wait for vault service to be registered
  wait_for:
    host: "{{ vault_host }}"
    port: "{{ vault_default_port }}"
    delay: 10
    timeout: 300
    state: present
  tags:
    - vault
