---
- name: prep docker creds folder
  file:
    path: /tmp/docker
    state: directory
  when: " docker_registries is defined "

- name: mount tmpfs on docker creds folder
  sudo: yes
  shell: mount -t tmpfs -o size=100M,mode=0640 tmpfs /tmp/docker
  when: " docker_registries is defined "

- name: write docker creds to tmpfs
  sudo: yes
  template:
    src: config.json.j2
    dest: /tmp/docker/config.json
  when: " docker_registries is defined "

- name: pull image
  sudo: yes
  shell: /usr/bin/docker --config=/tmp/docker/ pull {{ pull_image }}:{{ pull_image_tag }}

- name: unmount tmpfs on docker creds folder
  sudo: yes
  shell: umount /tmp/docker
  when: " docker_registries is defined "
